### ISSUE TITLE
Proximity Sensor Doesnt Work

### ISSUE THREAD

**Issue by zek** [react-native-webrtc/react-native-incall-manager#100]
I use iphone 7 plus with the latest iOS version.

Event never triggered and screen is always open.

~~~
import { DeviceEventEmitter } from 'react-native';
DeviceEventEmitter.addListener('Proximity', function (data) {
    // --- do something with events
});
~~~

**Comment by platonish** [comment]
Any updates on this?
@zek were you able to solve this?

**Comment by zek** [comment]
@platonish unfortunately I got no solution for it :'(

**Comment by zek** [comment]
Try this https://github.com/zek/react-native-incall-manager I guess I made it work

**Comment by swiety85** [comment]
May this be a solution: https://github.com/react-native-webrtc/react-native-incall-manager/issues/82#issuecomment-385241109 ?
