### ISSUE TITLE
Module RNInCallmanager requires main queue setup

### ISSUE THREAD

**Issue by varukashotta** [react-native-webrtc/react-native-incall-manager#102]
Hello, Thank you for the extension would you please help with a yellow box notification that shows on the latest RN installation and this extension which produces

>  Module RNInCallmanager requires main queue setup.......

![screen shot 2018-12-05 at 9 31 49 pm](https://user-images.githubusercontent.com/6804896/49516708-34103500-f8d5-11e8-83cc-1c84d4e21f68.png)

**Comment by ruddell** [comment]
This was fixed in https://github.com/zxcpoiu/react-native-incall-manager/pull/96, but not released yet.

**Comment by kayzenkayzen** [comment]
I have 3.2.2 and the warning not disappear.
