### ISSUE TITLE
React Native Webrtc candidates disconnected and failed when app is in background

### ISSUE THREAD

**Issue by murtazakaz** [react-native-webrtc/react-native-incall-manager#111]
I have implemented Webrtc

https://github.com/oney/react-native-webrtc

Audio Calling in react native project. Calling works perfect when app is in foreground both voices are clear but when app goes to background or user pressed home button, Call worked for around 8 ~ 15 seconds then its get disconnected with an error WebRTC ICE Candidates disconnected/Failed.

I have seen some of guys suggested to use

https://github.com/react-native-webrtc/react-native-callkeep

but I tried but couldn't run it as its documentation is not much clear to understand

I just want to get calling works perfect and webrtc even if app is in background.

**Comment by zxcpoiu** [comment]
Both iOS and Android add more restricted limitation for apps doing background task. Probably the right and the long-term-safe way is to integrate call-kit / connection service and request to enable backgroup/voip tags based on your platform.
