### ISSUE TITLE
Android: Can only use lower 16 bits for requestCode

### ISSUE THREAD

**Issue by maximovicd** [react-native-webrtc/react-native-incall-manager#115]
Since my upgrade to new React Native v0.59.9, I'm getting the following error on Android:

> Can only use lower 16 bits for requestCode

The issue seems to happen only on devices that haven't yet accepted the permissions, so this might explain why people are not reporting it. Can you confirm it's only a matter of changing the range in `InCallManagerModule` to `getRandomInteger(1, 65535);`?

**Comment by badver** [comment]
I had the same problem and fix it in my repo, PR created.
