### ISSUE TITLE
what is '$YOUR_VERSION' is?

### ISSUE THREAD

**Issue by Alarees** [react-native-webrtc/react-native-incall-manager#121]
in the installation guide:
> You should add compile "com.android.support:support-v4:$YOUR_VERSION" in $YOUR_PROJECT/android/app/build.gradle dependencies on android.
what is '$YOUR_VERSION' 
version of what, and where can i find it

**Comment by Alarees** [comment]
i used '${rootProject.ext.supportLibVersion}' instead of '$YOUR_VERSION', and problem solved

**Comment by linus-komnick** [comment]
'${rootProject.ext.supportLibVersion}' didn't work for me. This is what worked for me:
```
implementation (project(':react-native-incall-manager'))
implementation "com.android.support:support-v4:28.0.0"
implementation "com.android.support:appcompat-v7:28.0.0"
```
