### ISSUE TITLE
setSpeakerphoneOn on ios

### ISSUE THREAD

**Issue by sm2017** [react-native-webrtc/react-native-incall-manager#123]
setSpeakerphoneOn on iOS not works
it log `AudioSession override is successful` but not works

**Comment by sm2017** [comment]
@zxcpoiu after a year https://github.com/react-native-webrtc/react-native-incall-manager/issues/85
I still having issue with iOS loud speaker

Can you help me?

**Comment by zxcpoiu** [comment]
No clues at all :(

But I suggest you:

1. First, try not to use `setSpeakerPhone()` directly, use `InCallManager.start('video')` only to see if the sound routed to speakerphone.
2. check is there another plugin in your app also listen and modify the AudioSession singleton.
3. check / print the syslog to see the actual state of current AudioSession

**Comment by sm2017** [comment]
Fixed by using start not setSpeakerPhone directly

**Comment by trandinhhiep789** [comment]
Hi Sir, i wonder if we can just stop using setSpeakerPhone or have to InCallManager.start('video')? I don't have a real divces iphone to test =((, thanks sir

**Comment by KhNishad** [comment]
facing the same problem, setSpeakerphoneOn(false) is not working. I am wanting to mute the speaker in my audio video app.
