### ISSUE TITLE
If headphones / headset is connected before calling InCallManager.start(), headphones do not work unless unplugged and plugged back in again.

### ISSUE THREAD

**Issue by whenmoon** [react-native-webrtc/react-native-incall-manager#138]
I am making a calling app where users may or may not use headphones / a headset. On an incoming video call I am using [react-native-incall-manager][1] to turn the speaker on / allow speaker phone. The basic `InCallManager.start({ media: 'video' });` method works and allows detection of a new audio device being plugged in such as headphones, and if this happens, the headphone and mic plugged in work as expected.

The problem comes in the case that headphones are already plugged in to the device before a call starts. `InCallManager.start({ media: 'video' });` doesn't account for devices already connected and the headphones do not work, the normal speaker does even though headphones are plugged in.

The docs recommend using `DeviceEventEmitter` from react-native to detect native events such as changes in connected audio devices, but this module is [deprecated][2]. 

This from the readme, does nothing:

```javascript
import { DeviceEventEmitter } from 'react-native';

DeviceEventEmitter.addListener('WiredHeadset', function (data) {
    // --- do something with events
});
```

It is recommended to use `NativeEventEmitter`, but this seems very complex and seems to require the native Java (Android) modules to be written and used in conjunction with it.

What is the correct way to handle this?

  [1]: https://github.com/react-native-webrtc/react-native-incall-manager
  [2]: https://stackoverflow.com/questions/36692416/deviceeventemitter-vs-nativeappeventemitter

**Comment by tcsizmar** [comment]
@whenmoon Have you manage to get it working on iOS? I setup Native Modules but events are not firing up

**Comment by khushal87** [comment]
How did you solve it to android?
