### ISSUE TITLE
When forcing speaker mode on Android I cannot control the volume

### ISSUE THREAD

**Issue by jpudysz** [react-native-webrtc/react-native-incall-manager#141]
Steps to reproduce:
- enable `InCallManager`
- call `setSpeakerphoneOn(true)`
- try to change speaker volume by system physical buttons

Current behaviour:
- no change, no OS popup

Required behaviour:
- user can change speaker volume on the fly

Any ideas?

**Comment by mrsasuu** [comment]
Same here.

**Comment by andarg** [comment]
Will watch too:)

**Comment by CatsNipYummy** [comment]
Did you try enabling `<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />` ?

**Comment by irohitb** [comment]
@CatsNipYummy Yes, doesn't work

**Comment by habilpekdemir** [comment]
is there any update

**Comment by jpudysz** [comment]
I don't think so

**Comment by wilmxre** [comment]
any update on this?
