### ISSUE TITLE
iOS first app session - Earpiece/Speaker not working correctly

### ISSUE THREAD

**Issue by devWaleed** [react-native-webrtc/react-native-incall-manager#158]
I have identified this issue on iOS 14.2 and 14.3 and iOS 13.5.x

1. Install app from Testflight or from XCode first launch.
2. Make a WebRTC call
3. Call will be on Speaker and on button click, call manager will not switch it to earpiece
4. Close app
5. Restart app from clicking on the icon in iPhone
6. Make a WebRTC call
7. Call will be default on earpiece and speaker toggle will work correctly as required

Expected behavior:

Basically for first app launch, InCallManager setSpeakerPhoneOn doesn't work and call is on speaker, I have a button to toggle speaker/earpiece but it doesn't work if I call setSpeakerPhoneOn with true and false. If however I kill my app and start again, then everything starts working as expected. 

My code:

When Twilio Video WebRTC gives me a roomDidConnect event i.e the caller or receiver has connected to the Twilio video room:

    InCallManager.start({media: 'audio', auto: true});
    InCallManager.setForceSpeakerphoneOn(false);

and on roomDidDisconnect event:

    InCallManager.stop();

Console log for first session after Twilio video session has started and room has been joined succesfully:

```
default	17:43:39.697638+0500	MyApp	RNInCallManager.start(): recordPermission should be granted. state: undetermined
default	17:43:39.699062+0500	MyApp	RNInCallManager.setForceSpeakerphoneOn(): flag: -1
default	17:43:39.701281+0500	MyApp	RNInCallManager.updateAudioRoute(): [Enter] forceSpeakerOn flag=-1 media=audio category=AVAudioSessionCategoryPlayAndRecord mode=AVAudioSessionModeVideoChat
default	17:43:39.752701+0500	MyApp	RNInCallManager.updateAudioRoute(): audioSession.overrideOutputAudioPort(.None) success
default	17:43:39.752762+0500	MyApp	RNInCallManager.updateAudioRoute() did NOT change audio mode
```

Console log after I killed app and started again, then Twilio video session started and room was succesfully joined:

```
default	17:51:23.276969+0500	MyApp	RNInCallManager.start() start InCallManager. media=audio, type=audio, mode=AVAudioSessionModeVoiceChat
default	17:51:23.277832+0500	MyApp	RNInCallManager.storeOriginalAudioSetup(): origAudioCategory=AVAudioSessionCategoryPlayAndRecord, origAudioMode=AVAudioSessionModeVideoChat
default	17:51:23.278403+0500	MyApp	RNInCallManager.startAudioSessionNotification() starting...
default	2021-01-.27844906 17:51:23+0500	Artisan	RNInCallManager.startAudioSessionInterruptionNotification()
default	17:51:23.278492+0500	MyApp	RNInCallManager.startAudioSessionRouteChangeNotification()
default	17:51:23.278736+0500	MyApp	RNInCallManager.startAudioSessionMediaServicesWereLostNotification()
default	17:51:23.278815+0500	MyApp	RNInCallManager.startAudioSessionMediaServicesWereResetNotification()
default	17:51:23.278959+0500	MyApp	RNInCallManager.startAudioSessionSilenceSecondaryAudioHintNotification()
default	17:51:23.327450+0500	MyApp	RNInCallManager.start:auto:ringbackUriType:: audioSession.setCategory: AVAudioSessionCategoryPlayAndRecord, withOptions: 0 success
default	17:51:23.482465+0500	MyApp	RNInCallManager.start:auto:ringbackUriType:: audioSession.setMode(AVAudioSessionModeVoiceChat) success
default	17:51:23.487224+0500	MyApp	RNInCallManager.start:auto:ringbackUriType:: audioSession.setActive(YES), withOptions: 0 success
default	17:51:23.487912+0500	MyApp	RNInCallManager.startProximitySensor()
default	17:51:23.487981+0500	MyApp	RNInCallManager.setKeepScreenOn(): enable: YES
default	17:51:23.488040+0500	MyApp	RNInCallManager.setForceSpeakerphoneOn(): flag: -1
default	17:51:23.537580+0500	MyApp	RNInCallManager.updateAudioRoute(): [Enter] forceSpeakerOn flag=-1 media=audio category=AVAudioSessionCategoryPlayAndRecord mode=AVAudioSessionModeVoiceChat
default	17:51:23.565922+0500	MyApp	RNInCallManager.updateAudioRoute(): did NOT overrideOutputAudioPort()

```

**Comment by devWaleed** [comment]
@zxcpoiu can you try to replicate it sir?

**Comment by devWaleed** [comment]
After looking at the logs and then at the docs again...I see what's wrong. The other team mate didn't request the required record permission which caused in this issue.

Just added the following two lines on my first screen and this issue is resolved now:

```
if (InCallManager.recordPermission !== 'granted') {
        InCallManager.requestRecordPermission();
}
```

All works good (y)

**Comment by ilya-lopukhin** [comment]
Huge thanks @devWaleed, resolved my issue with iOS as well.
Wonder if it's something which is underdocumented and the method name itself is a bit misleading, requestRecordPermissions actually asks for local network access and microphone
