### ISSUE TITLE
speaker on/off not working on android 11

### ISSUE THREAD

**Issue by ghost** [react-native-webrtc/react-native-incall-manager#164]
setSpeakerphoneOn and setForceSpeakerphoneOn not working on android 11
when set speaker, the earphone sounds a little bit less, and the speaker no sound.
android 10 is working well.

**Comment by Richtervn** [comment]
My android 10 not work

**Comment by lahsuk** [comment]
You should add the `MODIFY_AUDIO_SETTINGS` to the manifest.

**Comment by dragoshuniq** [comment]
I have the same problem. Not working on Android 11-12. 
Already have `MODIFY_AUDIO_SETTINGS` , also tried both methods `setSpeakerphoneOn` and `setForceSpeakerphoneOn`.
Any solution so far ?

**Comment by KolissnikBogdan** [comment]
@dragoshuniq i also have same problem...

**Comment by KolissnikBogdan** [comment]
@dragoshuniq try to add this (InCallManagerModule.java)
<img width="934" alt="Снимок экрана 2022-09-02 в 17 04 59" src="https://user-images.githubusercontent.com/43568935/188166588-48b73ec7-4039-4d39-b27f-c726e6daa0b0.png">

**Comment by zxcpoiu** [comment]
fixed in #201
