### ISSUE TITLE
bluetooth headset

### ISSUE THREAD

**Issue by huseyindorudevtek** [react-native-webrtc/react-native-incall-manager#170]
After switching to speaker on android device not switching back to headphone
  if(enable)
            {
                InCallManager.setSpeakerphoneOn(true);
            }
            else
            {
                InCallManager.setSpeakerphoneOn(false);
                InCallManager.chooseAudioRoute('BLUETOOTH');
            }

**Comment by huseyindorudevtek** [comment]
InCallManager.start({ media: 'video' });
            if (speaker == SpeakerEnum.BLUETOOTH) {
                InCallManager.chooseAudioRoute('BLUETOOTH');
            }
            else if (speaker == SpeakerEnum.EARPIECE) {
                InCallManager.chooseAudioRoute('EARPIECE');
            }
            else if (speaker == SpeakerEnum.SPEAKER_PHONE) {
                InCallManager.chooseAudioRoute('SPEAKER_PHONE');
            }
            else if (speaker == SpeakerEnum.WIRED_HEADSET) {
                InCallManager.chooseAudioRoute('WIRED_HEADSET');
            }

**Comment by Pandazaur** [comment]
@consumadevtek Can you tell me what `speaker` is from ?

**Comment by yashecosmob** [comment]
by using InCallManager.chooseAudioRoute('BLUETOOTH'); this, audio route is not changing to bluetooth

**Comment by pierguinzani** [comment]
@yashecosmob, same here.
