### ISSUE TITLE
Not working on Android 12

### ISSUE THREAD

**Issue by davisuga** [react-native-webrtc/react-native-incall-manager#199]
When I use the library I get the following error
![image](https://user-images.githubusercontent.com/33470530/185809752-34fb6792-2172-444b-a100-baa87668baa7.png)
I added the `android.permission.BLUETOOTH_CONNECT` permission but it didn't work

**Comment by adriano-rodrigues99** [comment]
Hi, try something like this

`<uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
  <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
  <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />`

**Comment by davisuga** [comment]
Solved, thank you!
