### ISSUE TITLE
Custom ringtone issue

### ISSUE THREAD

**Issue by apadev555** [react-native-webrtc/react-native-incall-manager#202]
How can I set custom ringtone in IncallManager?
I've set incallmanager_ringtone.mp3 name to my custom audio file
but it always ringing the ios default ringtone

this is my call 
InCallManager.startRingtone('incallmanager_ringtone.mp3');

**Comment by fukemy** [comment]
hi, did u solved this? I want to apply my custom audio too

**Comment by saif-o99** [comment]
> hi, did u solved this? I want to apply my custom audio too

just put your mp3 inside this folder(check image) and the package will read it automatically

![image](https://user-images.githubusercontent.com/52207667/201122899-b14017dc-bb75-472e-b6d0-5be6af2ed473.png)

**Comment by variablemayank** [comment]
still not working
