### ISSUE TITLE
Error - Import of module 'glog.glog.log_severity' appears within namespace 'google'

### ISSUE THREAD

**Issue by ak47-arzooo** [react-native-webrtc/react-native-incall-manager#221]
<img width="1512" alt="Screenshot 2023-04-12 at 5 25 42 PM" src="https://user-images.githubusercontent.com/128481765/231713352-1532fc6f-ef94-4226-a40d-49ab1777ad0e.png">

"react-native": "0.66.5",
"react-native-incall-manager": "^4.0.0",

Xcode version - 14.2

**Comment by ak47-arzooo** [comment]
The above issue is coming for iOS BTW

**Comment by zxcpoiu** [comment]
closing since unrelated with this module
