### ISSUE TITLE
On ios not turning screen off 

### ISSUE THREAD

**Issue by bmp123** [react-native-webrtc/react-native-incall-manager#99]
Hi, I using InCallManager.start(). On Android if i hold the phone to my ear - screen turn off. But on IOS this doesn't work 
How can I fix it?

**Comment by bmp123** [comment]
any solutions??

**Comment by zxcpoiu** [comment]
It's proximity lock, no issue on my test.
Are you using version 3.2.2 ?

**Comment by zxcpoiu** [comment]
Maybe the related to #94 ?

**Comment by platonish** [comment]
@bmp123 what did you end up doing? The NativeModules solution suggested in #94 doesn't seem to work for me
